# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

QRV <- function(RR, V, W, pmk, Pk, tauR, tauV, EE) {
    .Call(`_LSEC_QRV`, RR, V, W, pmk, Pk, tauR, tauV, EE)
}

QUV <- function(SS, RR, U, V, W, pmk, Pk, Pmki1, Pmki2, tauS, tauR, tauU, tauV, EE, subsamp, IVApprox) {
    .Call(`_LSEC_QUV`, SS, RR, U, V, W, pmk, Pk, Pmki1, Pmki2, tauS, tauR, tauU, tauV, EE, subsamp, IVApprox)
}

QW <- function(SS, RR, U, V, W, pmk, Pk, EE, subsamp, IVApprox) {
    .Call(`_LSEC_QW`, SS, RR, U, V, W, pmk, Pk, EE, subsamp, IVApprox)
}

ahnGetDissimMat <- function(simMatij, EL) {
    .Call(`_LSEC_ahnGetDissimMat`, simMatij, EL)
}

computePmk <- function(SS, RR, U, V, W, alph, EE) {
    .Call(`_LSEC_computePmk`, SS, RR, U, V, W, alph, EE)
}

dQUV <- function(SS, RR, U, V, W, pmk, Pk, Pmki1, Pmki2, tauS, tauR, tauU, tauV, EE, subsamp, IVApprox) {
    .Call(`_LSEC_dQUV`, SS, RR, U, V, W, pmk, Pk, Pmki1, Pmki2, tauS, tauR, tauU, tauV, EE, subsamp, IVApprox)
}

dQW <- function(SS, RR, U, V, W, pmk, Pk, EE, subsamp, IVApprox) {
    .Call(`_LSEC_dQW`, SS, RR, U, V, W, pmk, Pk, EE, subsamp, IVApprox)
}

evalMargLogLik <- function(SS, RR, U, V, W, alph, EE, subsamp, IVApprox) {
    .Call(`_LSEC_evalMargLogLik`, SS, RR, U, V, W, alph, EE, subsamp, IVApprox)
}

evalMargPost <- function(SS, RR, U, V, W, tauS, tauR, tauU, tauV, alph, EE, a_s, b_s, a_r, b_r, a_u, a_v, b_u, b_v, a_0, subsamp, IVApprox) {
    .Call(`_LSEC_evalMargPost`, SS, RR, U, V, W, tauS, tauR, tauU, tauV, alph, EE, a_s, b_s, a_r, b_r, a_u, a_v, b_u, b_v, a_0, subsamp, IVApprox)
}

getPmki <- function(Pmk, Mi1Index, Mi1) {
    .Call(`_LSEC_getPmki`, Pmk, Mi1Index, Mi1)
}

indexEdges <- function(EE, n) {
    .Call(`_LSEC_indexEdges`, EE, n)
}

